
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author spa89
 */
public class MainFrame extends javax.swing.JFrame {
    DB_MAN DBM = new DB_MAN();
    String ID;
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ATMFrame = new javax.swing.JFrame();
        lblATMTitle = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        btnDeposit = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnLanguage = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnRank = new javax.swing.JButton();
        DepositFrame = new javax.swing.JFrame();
        txtDepoAmount = new javax.swing.JTextField();
        btnDepoConfirm = new javax.swing.JButton();
        lblDepoTitle = new javax.swing.JLabel();
        lblDepoAmount = new javax.swing.JLabel();
        lblDepoPass = new javax.swing.JLabel();
        txtDepoPass = new javax.swing.JTextField();
        WithdrawFrame = new javax.swing.JFrame();
        txtWithAmount = new javax.swing.JTextField();
        btnWithConfirm = new javax.swing.JButton();
        txtWithPass = new javax.swing.JTextField();
        lblWithPass = new javax.swing.JLabel();
        lblWithAmount = new javax.swing.JLabel();
        lblWithTitle = new javax.swing.JLabel();
        TransferFrame = new javax.swing.JFrame();
        txtTransAcc = new javax.swing.JTextField();
        btnTransConfirm = new javax.swing.JButton();
        txtTransAmount = new javax.swing.JTextField();
        txtTransPass = new javax.swing.JTextField();
        lblTransPass = new javax.swing.JLabel();
        lblTransAmount = new javax.swing.JLabel();
        lblTransTitle = new javax.swing.JLabel();
        lblTransAcc = new javax.swing.JLabel();
        ViewFrame = new javax.swing.JFrame();
        lblViewAcc = new javax.swing.JLabel();
        lblViewName = new javax.swing.JLabel();
        lblViewBalance = new javax.swing.JLabel();
        txtViewAcc = new javax.swing.JTextField();
        txtViewBalance = new javax.swing.JTextField();
        txtViewName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAreaView = new javax.swing.JTextArea();
        LoginFrame = new javax.swing.JFrame();
        txtID = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        lblLoginTitle = new javax.swing.JLabel();
        btnLoginConfirm = new javax.swing.JButton();
        RegisterFrame = new javax.swing.JFrame();
        lblRegTitle = new javax.swing.JLabel();
        lblRegName = new javax.swing.JLabel();
        lblRegID = new javax.swing.JLabel();
        lblRegPass = new javax.swing.JLabel();
        lblRegAccPass = new javax.swing.JLabel();
        lblRegPhone = new javax.swing.JLabel();
        btnRegConfirm = new javax.swing.JButton();
        txtRegName = new javax.swing.JTextField();
        txtRegID = new javax.swing.JTextField();
        txtRegPass = new javax.swing.JTextField();
        txtRegAccPass = new javax.swing.JTextField();
        txtRegPhone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        RankFrame = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        tAreaRank = new javax.swing.JTextArea();
        LanguageFrame = new javax.swing.JFrame();
        lblLanguageSelect = new javax.swing.JLabel();
        RadioKorean = new javax.swing.JRadioButton();
        RadioEnglish = new javax.swing.JRadioButton();
        RadioJapanese = new javax.swing.JRadioButton();
        btnLanguageSelect = new javax.swing.JButton();
        GroupLanguage = new javax.swing.ButtonGroup();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblMainTitle2 = new javax.swing.JLabel();
        lblMainTitle1 = new javax.swing.JLabel();

        lblATMTitle.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        lblATMTitle.setText("JAVA은행");

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.PNG"))); // NOI18N

        btnDeposit.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        btnDeposit.setText("입금");
        btnDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepositMouseClicked(evt);
            }
        });

        btnWithdraw.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        btnWithdraw.setText("출금");
        btnWithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWithdrawMouseClicked(evt);
            }
        });

        btnLanguage.setFont(new java.awt.Font("굴림", 1, 26)); // NOI18N
        btnLanguage.setText("언어교체");
        btnLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanguageActionPerformed(evt);
            }
        });

        btnTransfer.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        btnTransfer.setText("이체");
        btnTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransferMouseClicked(evt);
            }
        });

        btnView.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        btnView.setText("조회");
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMouseClicked(evt);
            }
        });

        btnRank.setFont(new java.awt.Font("굴림", 1, 26)); // NOI18N
        btnRank.setText("잔고랭킹");
        btnRank.setActionCommand("");
        btnRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ATMFrameLayout = new javax.swing.GroupLayout(ATMFrame.getContentPane());
        ATMFrame.getContentPane().setLayout(ATMFrameLayout);
        ATMFrameLayout.setHorizontalGroup(
            ATMFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ATMFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ATMFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addGroup(ATMFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRank, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(ATMFrameLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(lblATMTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ATMFrameLayout.setVerticalGroup(
            ATMFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ATMFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblATMTitle)
                .addGap(18, 18, 18)
                .addGroup(ATMFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ATMFrameLayout.createSequentialGroup()
                        .addComponent(lblImage)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(ATMFrameLayout.createSequentialGroup()
                        .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(ATMFrameLayout.createSequentialGroup()
                        .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnRank, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );

        DepositFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                DepositFrameWindowClosing(evt);
            }
        });

        txtDepoAmount.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N

        btnDepoConfirm.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        btnDepoConfirm.setText("입금");
        btnDepoConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepoConfirmActionPerformed(evt);
            }
        });

        lblDepoTitle.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        lblDepoTitle.setText("JAVA은행");

        lblDepoAmount.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblDepoAmount.setText("입금 금액");

        lblDepoPass.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblDepoPass.setText("계좌 비밀번호");

        txtDepoPass.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N

        javax.swing.GroupLayout DepositFrameLayout = new javax.swing.GroupLayout(DepositFrame.getContentPane());
        DepositFrame.getContentPane().setLayout(DepositFrameLayout);
        DepositFrameLayout.setHorizontalGroup(
            DepositFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDepoAmount)
                .addGap(47, 47, 47)
                .addComponent(txtDepoAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(DepositFrameLayout.createSequentialGroup()
                .addGroup(DepositFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DepositFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDepoPass)
                        .addGap(47, 47, 47)
                        .addComponent(txtDepoPass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DepositFrameLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnDepoConfirm))
                    .addGroup(DepositFrameLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblDepoTitle)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        DepositFrameLayout.setVerticalGroup(
            DepositFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDepoTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(DepositFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepoAmount)
                    .addComponent(txtDepoAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(DepositFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepoPass)
                    .addComponent(txtDepoPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(btnDepoConfirm)
                .addGap(31, 31, 31))
        );

        WithdrawFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                WithdrawFrameWindowClosing(evt);
            }
        });

        btnWithConfirm.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        btnWithConfirm.setText("출금");
        btnWithConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithConfirmActionPerformed(evt);
            }
        });

        txtWithPass.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N

        lblWithPass.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblWithPass.setText("계좌 비밀번호");

        lblWithAmount.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblWithAmount.setText("출금 금액");

        lblWithTitle.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        lblWithTitle.setText("JAVA은행");

        javax.swing.GroupLayout WithdrawFrameLayout = new javax.swing.GroupLayout(WithdrawFrame.getContentPane());
        WithdrawFrame.getContentPane().setLayout(WithdrawFrameLayout);
        WithdrawFrameLayout.setHorizontalGroup(
            WithdrawFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithdrawFrameLayout.createSequentialGroup()
                .addGroup(WithdrawFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WithdrawFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(WithdrawFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WithdrawFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblWithAmount))
                            .addComponent(lblWithPass))
                        .addGap(28, 28, 28)
                        .addGroup(WithdrawFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWithPass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWithAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(WithdrawFrameLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblWithTitle))
                    .addGroup(WithdrawFrameLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnWithConfirm)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        WithdrawFrameLayout.setVerticalGroup(
            WithdrawFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithdrawFrameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblWithTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(WithdrawFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWithAmount)
                    .addComponent(txtWithAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(WithdrawFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWithPass)
                    .addComponent(txtWithPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnWithConfirm)
                .addGap(38, 38, 38))
        );

        TransferFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                TransferFrameWindowClosing(evt);
            }
        });

        btnTransConfirm.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        btnTransConfirm.setText("이체");
        btnTransConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransConfirmActionPerformed(evt);
            }
        });

        txtTransPass.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N

        lblTransPass.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblTransPass.setText("계좌 비밀번호");

        lblTransAmount.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblTransAmount.setText("이체 금액");

        lblTransTitle.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        lblTransTitle.setText("JAVA은행");

        lblTransAcc.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblTransAcc.setText("이체 계좌");

        javax.swing.GroupLayout TransferFrameLayout = new javax.swing.GroupLayout(TransferFrame.getContentPane());
        TransferFrame.getContentPane().setLayout(TransferFrameLayout);
        TransferFrameLayout.setHorizontalGroup(
            TransferFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TransferFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTransPass)
                    .addComponent(lblTransAmount)
                    .addComponent(lblTransAcc))
                .addGap(69, 69, 69)
                .addGroup(TransferFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTransAcc)
                    .addComponent(txtTransAmount)
                    .addComponent(txtTransPass))
                .addContainerGap())
            .addGroup(TransferFrameLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btnTransConfirm)
                .addGap(0, 161, Short.MAX_VALUE))
            .addGroup(TransferFrameLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblTransTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TransferFrameLayout.setVerticalGroup(
            TransferFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTransTitle)
                .addGap(18, 18, 18)
                .addGroup(TransferFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTransAcc)
                    .addComponent(txtTransAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(TransferFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTransAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTransAmount))
                .addGap(18, 18, 18)
                .addGroup(TransferFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTransPass)
                    .addComponent(txtTransPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTransConfirm)
                .addGap(36, 36, 36))
        );

        ViewFrame.setSize(new java.awt.Dimension(500, 400));
        ViewFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                ViewFrameWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ViewFrameWindowClosing(evt);
            }
        });

        lblViewAcc.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        lblViewAcc.setText("계좌번호");

        lblViewName.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        lblViewName.setText("예금주명");

        lblViewBalance.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        lblViewBalance.setText("계좌 잔액");

        txtViewAcc.setEditable(false);

        txtViewBalance.setEditable(false);

        txtViewName.setEditable(false);

        tAreaView.setColumns(20);
        tAreaView.setRows(5);
        jScrollPane2.setViewportView(tAreaView);

        javax.swing.GroupLayout ViewFrameLayout = new javax.swing.GroupLayout(ViewFrame.getContentPane());
        ViewFrame.getContentPane().setLayout(ViewFrameLayout);
        ViewFrameLayout.setHorizontalGroup(
            ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewFrameLayout.createSequentialGroup()
                        .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblViewBalance, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblViewName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblViewAcc, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtViewName)
                            .addComponent(txtViewBalance)
                            .addComponent(txtViewAcc)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                .addContainerGap())
        );
        ViewFrameLayout.setVerticalGroup(
            ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewAcc)
                    .addComponent(txtViewAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewName)
                    .addComponent(txtViewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewBalance)
                    .addComponent(txtViewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        LoginFrame.setResizable(false);

        txtID.setForeground(new java.awt.Color(204, 204, 204));
        txtID.setText("ID");
        txtID.setToolTipText("");
        txtID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIDMousePressed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });

        txtPass.setForeground(new java.awt.Color(204, 204, 204));
        txtPass.setText("Password");
        txtPass.setToolTipText("");
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassMousePressed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });

        lblLoginTitle.setFont(new java.awt.Font("굴림", 0, 48)); // NOI18N
        lblLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginTitle.setText("JAVA은행");

        btnLoginConfirm.setText("로그인");
        btnLoginConfirm.setActionCommand("");
        btnLoginConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginConfirmMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginFrameLayout = new javax.swing.GroupLayout(LoginFrame.getContentPane());
        LoginFrame.getContentPane().setLayout(LoginFrameLayout);
        LoginFrameLayout.setHorizontalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                    .addGroup(LoginFrameLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnLoginConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginFrameLayout.setVerticalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnLoginConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        lblRegTitle.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        lblRegTitle.setText("JAVA은행 회원가입");

        lblRegName.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblRegName.setText("이름");

        lblRegID.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblRegID.setText("아이디");

        lblRegPass.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblRegPass.setText("비밀번호");

        lblRegAccPass.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblRegAccPass.setText("계좌 비밀번호");

        lblRegPhone.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        lblRegPhone.setText("핸드폰번호");

        btnRegConfirm.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        btnRegConfirm.setText("회원가입");
        btnRegConfirm.setActionCommand("");
        btnRegConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegConfirmMouseClicked(evt);
            }
        });

        txtRegName.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N

        txtRegID.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N

        txtRegPass.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N

        txtRegAccPass.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N

        txtRegPhone.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N

        javax.swing.GroupLayout RegisterFrameLayout = new javax.swing.GroupLayout(RegisterFrame.getContentPane());
        RegisterFrame.getContentPane().setLayout(RegisterFrameLayout);
        RegisterFrameLayout.setHorizontalGroup(
            RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterFrameLayout.createSequentialGroup()
                        .addComponent(btnRegConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterFrameLayout.createSequentialGroup()
                        .addGroup(RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RegisterFrameLayout.createSequentialGroup()
                                .addGroup(RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRegID)
                                    .addComponent(lblRegPass)
                                    .addComponent(lblRegAccPass)
                                    .addComponent(lblRegPhone)
                                    .addComponent(lblRegName))
                                .addGroup(RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegisterFrameLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(txtRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterFrameLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRegPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRegAccPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRegPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRegID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(lblRegTitle))
                        .addGap(38, 38, 38))))
        );
        RegisterFrameLayout.setVerticalGroup(
            RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegTitle)
                .addGap(31, 31, 31)
                .addGroup(RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegName)
                    .addComponent(txtRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRegID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegID, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRegPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegPass))
                .addGap(18, 18, 18)
                .addGroup(RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegAccPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegAccPass))
                .addGap(18, 18, 18)
                .addGroup(RegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegPhone)
                    .addComponent(txtRegPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnRegConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        RankFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                RankFrameWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                RankFrameWindowClosing(evt);
            }
        });

        tAreaRank.setColumns(20);
        tAreaRank.setRows(5);
        jScrollPane3.setViewportView(tAreaRank);

        javax.swing.GroupLayout RankFrameLayout = new javax.swing.GroupLayout(RankFrame.getContentPane());
        RankFrame.getContentPane().setLayout(RankFrameLayout);
        RankFrameLayout.setHorizontalGroup(
            RankFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        RankFrameLayout.setVerticalGroup(
            RankFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        lblLanguageSelect.setFont(new java.awt.Font("맑은 고딕", 0, 48)); // NOI18N
        lblLanguageSelect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLanguageSelect.setText("언어 선택");

        GroupLanguage.add(RadioKorean);
        RadioKorean.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        RadioKorean.setText("한국어");

        GroupLanguage.add(RadioEnglish);
        RadioEnglish.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        RadioEnglish.setText("English");

        GroupLanguage.add(RadioJapanese);
        RadioJapanese.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        RadioJapanese.setText("日本語");

        btnLanguageSelect.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        btnLanguageSelect.setText("선택");
        btnLanguageSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanguageSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LanguageFrameLayout = new javax.swing.GroupLayout(LanguageFrame.getContentPane());
        LanguageFrame.getContentPane().setLayout(LanguageFrameLayout);
        LanguageFrameLayout.setHorizontalGroup(
            LanguageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LanguageFrameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblLanguageSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(LanguageFrameLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(RadioKorean)
                .addGap(59, 59, 59)
                .addComponent(RadioEnglish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RadioJapanese)
                .addGap(31, 31, 31))
            .addGroup(LanguageFrameLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnLanguageSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LanguageFrameLayout.setVerticalGroup(
            LanguageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LanguageFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLanguageSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(LanguageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioEnglish)
                    .addComponent(RadioKorean)
                    .addComponent(RadioJapanese))
                .addGap(56, 56, 56)
                .addComponent(btnLanguageSelect)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegister.setFont(new java.awt.Font("굴림", 0, 40)); // NOI18N
        btnRegister.setText("회원가입");
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("굴림", 0, 40)); // NOI18N
        btnLogin.setText("로그인");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        lblMainTitle2.setFont(new java.awt.Font("굴림", 0, 48)); // NOI18N
        lblMainTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainTitle2.setText("ATM");

        lblMainTitle1.setFont(new java.awt.Font("굴림", 0, 48)); // NOI18N
        lblMainTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainTitle1.setText("JAVA은행");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMainTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMainTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMainTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMainTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        LoginFrame.setLocation(1000,500);
        LoginFrame.setSize(400, 300);
        LoginFrame.setVisible(true);
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositMouseClicked
        DepositFrame.setLocation(1000,500);
        DepositFrame.setSize(350, 300);
        DepositFrame.setVisible(true);
        ATMFrame.setVisible(false);
    }//GEN-LAST:event_btnDepositMouseClicked

    private void btnWithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWithdrawMouseClicked
        WithdrawFrame.setLocation(1000,500);
        WithdrawFrame.setSize(350, 300);
        WithdrawFrame.setVisible(true);
        ATMFrame.setVisible(false);
    }//GEN-LAST:event_btnWithdrawMouseClicked

    private void btnTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferMouseClicked
        TransferFrame.setLocation(1000,500);
        TransferFrame.setSize(380, 300);
        TransferFrame.setVisible(true);
        ATMFrame.setVisible(false);
    }//GEN-LAST:event_btnTransferMouseClicked

    private void btnViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseClicked
        ViewFrame.setLocation(1000, 500);
        ViewFrame.setSize(500, 400);
        ViewFrame.setVisible(true);
        ATMFrame.setVisible(false);
    }//GEN-LAST:event_btnViewMouseClicked

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        RegisterFrame.setLocation(1000, 500);
        RegisterFrame.setSize(380, 430);
        RegisterFrame.setVisible(true);
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void btnLoginConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginConfirmMouseClicked
        /* 로그인 시 발생하는 이벤트 */
        ID = txtID.getText();  // ID 전역 변수에 내 id를 할당
        String password = txtPass.getText();
        String strSQL = "SELECT * FROM user WHERE id = '" + ID + "'";
        
        try {
            DBM.dbOpen();
            try {
                DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
                if (DBM.DB_rs.next()) {   // DB에 아이디가 존재 하는가?
                    if (password.equals(DBM.DB_rs.getString("pass"))) {   // 암호가 같다면
                        /* 로그인 성공 */
                        JOptionPane.showMessageDialog(null, ID + "님 로그인에 성공하였습니다.");
                        DBM.dbClose();
                        
                        LoginFrame.setVisible(false);
                        ATMFrame.setLocation(1000,500);
                        ATMFrame.setSize(660,500);
                        ATMFrame.setVisible(true);  // ATM 메인 화면을 띄워줌
                        txtID.setText("");
                        txtPass.setText("");
                    } else {   // 암호가 같지 않다면
                        JOptionPane.showMessageDialog(null, "비밀번호가 틀렸습니다.");
                        DBM.dbClose();
                    }
                    
                } else {   // 아이디가 존재하지 않다면
                    JOptionPane.showMessageDialog(null, "로그인 실패!");
                    DBM.dbClose();
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                DBM.dbClose();
            }
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);           
        }
    }//GEN-LAST:event_btnLoginConfirmMouseClicked

    private void btnRegConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegConfirmMouseClicked
        /* 회원가입 시 발생하는 이벤트 */
        String name = txtRegName.getText();
        String id = txtRegID.getText();   
        boolean check = true;
        try{
            DBM.dbOpen();
            String strSQL = "SELECT * FROM user";
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            if(DBM.DB_rs.next()){
            while (DBM.DB_rs.next()){
                if (id.equals(DBM.DB_rs.getString("id"))) {
                    check = false;
                    DBM.dbClose();
                    JOptionPane.showMessageDialog(null, "아이디가 중복됩니다!");  
                    break;
                }                
            }}
            DBM.dbClose();            
        }catch (IOException | SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(check){
        String password = txtRegPass.getText();
        String accPass = txtRegAccPass.getText();
        String phone = txtRegPhone.getText();
        int balance = 0;
        Random r = new Random();
        
        String accNo = "1999";
        for (int i = 0; i < 8; i++) {   // 무작위 난수의 계좌번호 생성
            accNo += Integer.toString(r.nextInt(10));
        }
       
        String strSQL = "INSERT INTO user VALUES('" + name + "', '" + id + "', '" + password + "', " + balance 
                            + ", '"+ accNo + "', '" + accPass + "', '" + phone + "')";

        try {
            DBM.dbOpen();
            
            try {
                int result = DBM.DB_stmt.executeUpdate(strSQL);
                if (result != 0) {  // 회원가입에 성공한 경우 (삽입한 레코드의 수) 
                    ID = id;
                    JOptionPane.showMessageDialog(null, id + "님 회원가입에 성공하였습니다.\n당신의 계좌번호는 " + accNo + "입니다.");
                    RegisterFrame.setVisible(false);
                    DBM.dbClose();
                    
                } else {  // 회원가입에 실패한 경우 (레코드 삽입 실패)
                    JOptionPane.showMessageDialog(null, "회원가입에 실패하셨습니다.");
                    DBM.dbClose();
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnRegConfirmMouseClicked

    private void DepositFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_DepositFrameWindowClosing
        // TODO add your handling code here:
        ATMFrame.setLocation(1000,500);
        ATMFrame.setSize(660,500);
        ATMFrame.setVisible(true);
    }//GEN-LAST:event_DepositFrameWindowClosing

    private void WithdrawFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WithdrawFrameWindowClosing
        // TODO add your handling code here:
        ATMFrame.setLocation(1000,500);
        ATMFrame.setSize(660,500);
        ATMFrame.setVisible(true);
    }//GEN-LAST:event_WithdrawFrameWindowClosing

    private void TransferFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_TransferFrameWindowClosing
        // TODO add your handling code here:
        ATMFrame.setLocation(1000, 500);
        ATMFrame.setSize(660, 500);
        ATMFrame.setVisible(true);
    }//GEN-LAST:event_TransferFrameWindowClosing

    private void btnDepoConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepoConfirmActionPerformed
        /* 입금 시에 발생하는 이벤트 */
        int amount = Integer.parseInt(txtDepoAmount.getText());  // 입금 금액
        String pass = txtDepoPass.getText();    // 계좌 비밀번호
        
        try {
            DBM.dbOpen();
            
            try {
                String strSQL = "SELECT * FROM user WHERE id = '" + ID + "'";
                DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
                
                if (DBM.DB_rs.next()) {  // 아이디가 DB에 존재하는가?
                    if (DBM.DB_rs.getString("accountPass").equals(pass)) {  // 계좌 비밀번호가 일치하는가?
                        String accNo = DBM.DB_rs.getString("accountNo");    // 계좌 번호
                        int balance = Integer.parseInt(DBM.DB_rs.getString("balance"));  // 계좌 잔액
                        String currentDate = format.format(System.currentTimeMillis());  // 현재 날짜
                        
                        balance += amount;
                        JOptionPane.showMessageDialog(null, ID + "님 " + amount + "원 입금되었습니다.\n잔액: " + balance);
                        
                        String updateSQL = "UPDATE user SET balance = " + balance + " WHERE id = '" + ID + "'";
                        DBM.DB_stmt.executeUpdate(updateSQL); // 잔액 갱신
                        
                        String insertSQL = 
                                "INSERT INTO transaction VALUES('" + accNo + "', '입금', " + amount + ", '', '" + currentDate + "')";
                        DBM.DB_stmt.executeUpdate(insertSQL); // 거래 내역 갱신
                        
                        DBM.dbClose();
                        
                    } else {  // 입력한 계좌 비밀번호가 다른 경우
                        JOptionPane.showMessageDialog(null, "계좌 비밀번호가 다릅니다.");
                        DBM.dbClose();
                    }
                    
                } else {  // 아이디가 DB에 존재하지 않은 경우
                    JOptionPane.showMessageDialog(null, "입금에 실패하였습니다.");
                    DBM.dbClose();
                }
                
                txtDepoAmount.setText(null);
                txtDepoPass.setText(null);
                
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                DBM.dbClose();
            }
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);           
        }
    }//GEN-LAST:event_btnDepoConfirmActionPerformed

    private void btnWithConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithConfirmActionPerformed
        /* 출금 시에 발생하는 이벤트 */
        int amount = Integer.parseInt(txtWithAmount.getText());  // 출금 금액
        String pass = txtWithPass.getText();    // 계좌 비밀번호
        
        try {
            DBM.dbOpen();
            
            try {
                String strSQL = "SELECT * FROM user WHERE id = '" + ID + "'";
                DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
                
                if (DBM.DB_rs.next()) {  // 아이디가 DB에 존재하는가?
                    if (DBM.DB_rs.getString("accountPass").equals(pass)) {  // 계좌 비밀번호가 일치하는가?
                        String accNo = DBM.DB_rs.getString("accountNo");    // 계좌 번호
                        int balance = Integer.parseInt(DBM.DB_rs.getString("balance"));  // 계좌 잔액
                        String currentDate = format.format(System.currentTimeMillis());  // 현재 날짜
                        
                        if (balance >= amount) {
                        balance -= amount;
                        JOptionPane.showMessageDialog(null, ID + "님 " + amount + "원 출금되었습니다.\n잔액: " + balance);
                        
                        String updateSQL = "UPDATE user SET balance = " + balance + " WHERE id = '" + ID + "'";
                        DBM.DB_stmt.executeUpdate(updateSQL); // 잔액 갱신
                        
                        String insertSQL = 
                                "INSERT INTO transaction VALUES('" + accNo + "', '출금', " + amount + ", '', '" + currentDate + "')";
                        DBM.DB_stmt.executeUpdate(insertSQL); // 거래 내역 갱신
                        DBM.dbClose();
                        
                        } else {
                            JOptionPane.showMessageDialog(null, "잔액이 부족합니다.");
                            DBM.dbClose();
                        }
                    } else {  // 입력한 계좌 비밀번호가 다른 경우
                        JOptionPane.showMessageDialog(null, "계좌 비밀번호가 다릅니다.");
                        DBM.dbClose();
                    }
                    
                } else {  // 아이디가 DB에 존재하지 않은 경우
                    JOptionPane.showMessageDialog(null, "출금에 실패하였습니다.");
                    DBM.dbClose();
                }
                
                txtWithAmount.setText(null);
                txtWithPass.setText(null);
                
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                DBM.dbClose();
            }
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);           
        }
    }//GEN-LAST:event_btnWithConfirmActionPerformed

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        /* 미리보기 텍스트 구현 */
        if (txtID.getForeground() != Color.BLACK) {
            if (txtID.getText().equals("ID")) {
                txtID.setText("");
            }
        }
        txtID.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtIDKeyPressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        /* 미리보기 텍스트 구현 */
        if (txtPass.getForeground() != Color.BLACK) {
            if (txtPass.getText().equals("Password")) {
                txtPass.setText("");
            }
        }
        txtPass.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtPassKeyPressed

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
        /* 미리보기 텍스트 구현 */
        if (txtID.getText().isEmpty() == true) {
            txtID.setText("ID");
            txtID.setCaretPosition(0);
            txtID.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtIDKeyReleased

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        /* 미리보기 텍스트 구현 */
        if (txtPass.getText().isEmpty() == true) {
            txtPass.setText("Password");
            txtPass.setCaretPosition(0);
            txtPass.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtPassKeyReleased

    private void txtIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMousePressed
        /* 미리보기 텍스트 구현 */
        txtID.setCaretPosition(0);
    }//GEN-LAST:event_txtIDMousePressed

    private void txtPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMousePressed
        /* 미리보기 텍스트 구현 */
        txtPass.setCaretPosition(0);
    }//GEN-LAST:event_txtPassMousePressed

    private void btnTransConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransConfirmActionPerformed
        /* 이체 시에 발생하는 이벤트 */
        int amount = Integer.parseInt(txtTransAmount.getText());  // 이체 금액
        String pass = txtTransPass.getText();    // 계좌 비밀번호
        String transAcc = txtTransAcc.getText(); // 상대 계좌번호
        String currentDate = format.format(System.currentTimeMillis());  // 현재 날짜
        
        try {
            DBM.dbOpen();
            
            try {
                String strSQL = "SELECT * FROM user WHERE id = '" + ID + "'";
                DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
                
                if (DBM.DB_rs.next()) {  // 아이디가 DB에 존재하는가?
                    if (DBM.DB_rs.getString("accountPass").equals(pass)) {  // 계좌 비밀번호가 일치하는가?
                        String accNo = DBM.DB_rs.getString("accountNo");    // 내 계좌 번호
                        int balance = Integer.parseInt(DBM.DB_rs.getString("balance"));  // 내 계좌 잔액
                        
                        if (balance >= amount) {  // 계좌 잔액이 충분한 경우
                            String updateSQL = "UPDATE user SET balance = " + balance + " WHERE id = '" + ID + "'";
                            DBM.DB_stmt.executeUpdate(updateSQL); // 내 계좌 잔액 갱신
                            balance -= amount;
                            
                            String transName = transfer(transAcc, amount); 
                            // 함수로 상대계좌랑 이체금액 매개변수로 보내서 처리 리턴으로 상대 이름(거래내역때 쓰려고) 받아옴
                            if (transName != null) {  // 상대 계좌번호를 발견 못한 경우                                
                                JOptionPane.showMessageDialog(null, ID + "님 " + transName + "님에게" + amount + "원 이체되었습니다.\n잔액: " + balance);

                                String insertSQL = "INSERT INTO transaction VALUES('" + accNo + "', '이체', " + amount + ",'" + transName+"("+accNo+")" + "','"+currentDate+"')";
                                DBM.DB_stmt.executeUpdate(insertSQL); // 거래 내역 갱신
                                DBM.dbClose();
                                
                            } else {
                                JOptionPane.showMessageDialog(null, "올바르지 않은 계좌번호 입니다.");
                                DBM.dbClose();
                            }
                            
                        } else {  // 계좌 잔액이 부족한 경우
                            JOptionPane.showMessageDialog(null, "계좌 잔액이 부족합니다.");
                            DBM.dbClose();
                        }
                        
                    } else {  // 입력한 계좌 비밀번호가 다른 경우
                        JOptionPane.showMessageDialog(null, "계좌 비밀번호가 다릅니다.");
                        DBM.dbClose();
                    }
                    
                } else {  // 아이디가 DB에 존재하지 않은 경우
                    JOptionPane.showMessageDialog(null, "이체에 실패하였습니다.");
                    DBM.dbClose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                DBM.dbClose();
            }
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);           
        }
    }//GEN-LAST:event_btnTransConfirmActionPerformed

    private void ViewFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ViewFrameWindowActivated
        /* 조회 시에 발생하는 이벤트 */
        try {
            DBM.dbOpen();
            
            try {
                String strSQL = "SELECT * FROM user WHERE id = '" + ID + "'";
                DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);  // 현재 사용자의 정보를 끌어옴
                
                if (DBM.DB_rs.next()) {  // 현재 사용자의 정보가 존재 하는가?
                    String accountNo = DBM.DB_rs.getString("accountNo");  // 계좌번호
                    String name = DBM.DB_rs.getString("name");            // 이름
                    String balance = DBM.DB_rs.getString("balance");      // 계좌 잔액
                    txtViewAcc.setText(accountNo);
                    txtViewName.setText(name);
                    txtViewBalance.setText(balance);
                    
                    strSQL = "SELECT * FROM transaction WHERE accountNo = '" + accountNo + "'";
                    DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);  // 현재 사용자의 거래 내역을 끌어옴
                    String viewResult = "거래일\t구분\t거래금액\t입금처\n";
                    
                    while (DBM.DB_rs.next()) {
                        /* 형식: 거래일, 구분, 거래금액, 입금처 */
                        String date = DBM.DB_rs.getString("date");      // 거래일
                        String type = DBM.DB_rs.getString("type");      // 구분
                        String amount = DBM.DB_rs.getString("amount");  // 거래금액
                        String target = DBM.DB_rs.getString("target");  // 입금처
                        
                        viewResult += (date + "\t");
                        viewResult += (type + "\t");
                        viewResult += (amount + "\t");
                        viewResult += (target + "\t\n");
                    }
                    
                    tAreaView.setText(viewResult);
                    DBM.dbClose();
                    
                } else {  // 사용자의 정보가 존재하지 않을 경우
                    JOptionPane.showMessageDialog(null, "사용자의 정보가 존재하지 않습니다.");
                    ViewFrame.setVisible(false);
                    ATMFrame.setVisible(true);
                    DBM.dbClose();
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                DBM.dbClose();
            }
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);           
        }
    }//GEN-LAST:event_ViewFrameWindowActivated

    private void ViewFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ViewFrameWindowClosing
        /* 조회화면을 닫을 때 발생하는 이벤트 */
        ATMFrame.setLocation(1000, 500);
        ATMFrame.setSize(660, 500);
        ATMFrame.setVisible(true);
    }//GEN-LAST:event_ViewFrameWindowClosing

    private void btnRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankActionPerformed
        RankFrame.setLocation(1000, 500);
        RankFrame.setSize(500, 400);
        RankFrame.setVisible(true);
        ATMFrame.setVisible(false);
    }//GEN-LAST:event_btnRankActionPerformed

    private void RankFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RankFrameWindowActivated
        try {
            DBM.dbOpen();
            
            try {
                String strSQL = "SELECT * FROM user ORDER BY balance DESC"; // 돈 많은 순서대로 select 함
                DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);  // 현재 사용자의 정보를 끌어옴
                String viewResult = "순위\t이름\t계좌번호\t잔고\n";
                int i = 1;  // 순위 인덱스
                
                if (DBM.DB_rs.next()) { 
                    do {
                        String accountNo = DBM.DB_rs.getString("accountNo");  // 계좌번호
                        String name = DBM.DB_rs.getString("name");            // 이름
                        String balance = DBM.DB_rs.getString("balance");      // 계좌 잔액
                        viewResult += (i + "\t");
                        viewResult += (name + "\t");
                        viewResult += (accountNo + "\t");
                        viewResult += (balance + "\t\n");
                        i++;
                    } while (DBM.DB_rs.next());
                    tAreaRank.setText(viewResult);
                    
                } else {  // 사용자의 정보가 존재하지 않을 경우
                    JOptionPane.showMessageDialog(null, "랭킹을 불러올 수 없습니다.");
                    ViewFrame.setVisible(false);
                    ATMFrame.setVisible(true);
                    DBM.dbClose();
                }
                DBM.dbClose();
                
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                DBM.dbClose();
            }
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);           
        }
    }//GEN-LAST:event_RankFrameWindowActivated

    private void RankFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RankFrameWindowClosing
        ATMFrame.setLocation(1000, 500);
        ATMFrame.setSize(660, 500);
        ATMFrame.setVisible(true);
    }//GEN-LAST:event_RankFrameWindowClosing

    private void btnLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanguageActionPerformed
        /* 언어교체 버튼 클릭 시 발생하는 이벤트 */
        LanguageFrame.setLocation(1000, 500);
        LanguageFrame.setSize(400, 280);
        LanguageFrame.setVisible(true);
        ATMFrame.setVisible(false);
    }//GEN-LAST:event_btnLanguageActionPerformed

    private void btnLanguageSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanguageSelectActionPerformed
        /* 언어 선택 후, 버튼 클릭 시 발생하는 이벤트*/
        ATMFrame.setLocation(1000, 500);
        ATMFrame.setSize(660, 500);
        ATMFrame.setVisible(true);
        LanguageFrame.setVisible(false);
        
        if (RadioKorean.isSelected()) {  // 한국어
            lblMainTitle1.setText("JAVA은행");
            btnLogin.setText("로그인");
            btnRegister.setText("회원가입");
            lblATMTitle.setText("JAVA은행");
            btnDeposit.setText("입금");
            btnWithdraw.setText("출금");
            btnLanguage.setText("언어교체");
            btnTransfer.setText("이체");
            btnView.setText("조회");
            btnRank.setText("잔고랭킹");
            lblDepoTitle.setText("JAVA은행");
            lblDepoAmount.setText("입금 금액");
            lblDepoPass.setText("계좌 비밀번호");
            btnDepoConfirm.setText("입금");
            lblWithTitle.setText("JAVA은행");
            lblWithAmount.setText("출금 금액");
            lblWithPass.setText("계좌 비밀번호");
            btnWithConfirm.setText("출금");
            lblTransTitle.setText("JAVA은행");
            lblTransAcc.setText("이체 계좌");
            lblTransAmount.setText("출금 금액");
            lblTransPass.setText("계좌 비밀번호");
            btnTransConfirm.setText("이체");
            lblViewAcc.setText("계좌번호");
            lblViewName.setText("예금주명");
            lblViewBalance.setText("계좌 잔액");
            lblRegTitle.setText("JAVA은행 회원가입");
            lblRegName.setText("이름");
            lblRegID.setText("아이디");
            lblRegPass.setText("비밀번호");
            lblRegAccPass.setText("계좌 비밀번호");
            lblRegPhone.setText("핸드폰 번호");
            btnRegConfirm.setText("회원가입");
            lblLanguageSelect.setText("언어 선택");
            btnLanguageSelect.setText("선택");
            lblLoginTitle.setText("JAVA은행");
            btnLoginConfirm.setText("로그인");
            
            lblMainTitle1.setFont(new java.awt.Font("Malgun Gothic", 1, 36));
            btnLogin.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            btnRegister.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblATMTitle.setFont(new java.awt.Font("Malgun Gothic", 1, 36));
            btnDeposit.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            btnWithdraw.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            btnLanguage.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            btnTransfer.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            btnView.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            btnRank.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblDepoTitle.setFont(new java.awt.Font("Malgun Gothic", 1, 36));
            lblDepoAmount.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblDepoPass.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            btnDepoConfirm.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblWithTitle.setFont(new java.awt.Font("Malgun Gothic", 1, 36));
            lblWithAmount.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblWithPass.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            btnWithConfirm.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblTransTitle.setFont(new java.awt.Font("Malgun Gothic", 1, 36));
            lblTransAcc.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblTransAmount.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblTransPass.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            btnTransConfirm.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblViewAcc.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblViewName.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblViewBalance.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblRegTitle.setFont(new java.awt.Font("Malgun Gothic", 1, 36));
            lblRegName.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblRegID.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblRegPass.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblRegAccPass.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblRegPhone.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            btnRegConfirm.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblLanguageSelect.setFont(new java.awt.Font("Malgun Gothic", 1, 36));
            btnLanguageSelect.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            lblLoginTitle.setFont(new java.awt.Font("Malgun Gothic", 1, 36));
            btnLoginConfirm.setFont(new java.awt.Font("Malgun Gothic", 1, 20));
            
        } else if (RadioEnglish.isSelected()) {   // 영어
            lblMainTitle1.setText("JAVA Bank");
            btnLogin.setText("Sign in");
            btnRegister.setText("Register");
            lblATMTitle.setText("JAVA Bank");
            btnDeposit.setText("Deposit");
            btnWithdraw.setText("Withdrawal");
            btnLanguage.setText("Change \nLanguage");
            btnTransfer.setText("Transfer");
            btnView.setText("View \nAccount Info");
            btnRank.setText("Balance \nRanking");
            lblDepoTitle.setText("JAVA Bank");
            lblDepoAmount.setText("Amount");
            lblDepoPass.setText("Account \nPassword");
            btnDepoConfirm.setText("Deposit");
            lblWithTitle.setText("JAVA Bank");
            lblWithAmount.setText("Amount");
            lblWithPass.setText("Account \nPassword");
            btnWithConfirm.setText("Withdraw");
            lblTransTitle.setText("JAVA Bank");
            lblTransAcc.setText("Transfer \nAccount");
            lblTransAmount.setText("Amount");
            lblTransPass.setText("Account \nPassword");
            btnTransConfirm.setText("Transfer");
            lblViewAcc.setText("Account No.");
            lblViewName.setText("Name");
            lblViewBalance.setText("Balance");
            lblRegTitle.setText("Register");
            lblRegName.setText("Name");
            lblRegID.setText("ID");
            lblRegPass.setText("Password");
            lblRegAccPass.setText("Account \nPassword");
            lblRegPhone.setText("Phone Number");
            btnRegConfirm.setText("Register");
            lblLanguageSelect.setText("Change \nLanguage");
            btnLanguageSelect.setText("Select");
            lblLoginTitle.setText("JAVA Bank");
            btnLoginConfirm.setText("Sign in");
            
            lblMainTitle1.setFont(new java.awt.Font("Arial", 1, 36));
            btnLogin.setFont(new java.awt.Font("Arial", 1, 13));
            btnRegister.setFont(new java.awt.Font("Arial", 1, 13));
            lblATMTitle.setFont(new java.awt.Font("Arial", 1, 36));
            btnDeposit.setFont(new java.awt.Font("Arial", 1, 13));
            btnWithdraw.setFont(new java.awt.Font("Arial", 1, 13));
            btnLanguage.setFont(new java.awt.Font("Arial", 1, 13));
            btnTransfer.setFont(new java.awt.Font("Arial", 1, 13));
            btnView.setFont(new java.awt.Font("Arial", 1, 13));
            btnRank.setFont(new java.awt.Font("Arial", 1, 13));
            lblDepoTitle.setFont(new java.awt.Font("Arial", 1, 36));
            lblDepoAmount.setFont(new java.awt.Font("Arial", 1, 13));
            lblDepoPass.setFont(new java.awt.Font("Arial", 1, 13));
            btnDepoConfirm.setFont(new java.awt.Font("Arial", 1, 13));
            lblWithTitle.setFont(new java.awt.Font("Arial", 1, 36));
            lblWithAmount.setFont(new java.awt.Font("Arial", 1, 13));
            lblWithPass.setFont(new java.awt.Font("Arial", 1, 13));
            btnWithConfirm.setFont(new java.awt.Font("Arial", 1, 13));
            lblTransTitle.setFont(new java.awt.Font("Arial", 1, 36));
            lblTransAcc.setFont(new java.awt.Font("Arial", 1, 13));
            lblTransAmount.setFont(new java.awt.Font("Arial", 1, 13));
            lblTransPass.setFont(new java.awt.Font("Arial", 1, 13));
            btnTransConfirm.setFont(new java.awt.Font("Arial", 1, 13));
            lblViewAcc.setFont(new java.awt.Font("Arial", 1, 13));
            lblViewName.setFont(new java.awt.Font("Arial", 1, 13));
            lblViewBalance.setFont(new java.awt.Font("Arial", 1, 13));
            lblRegTitle.setFont(new java.awt.Font("Arial", 1, 36));
            lblRegName.setFont(new java.awt.Font("Arial", 1, 13));
            lblRegID.setFont(new java.awt.Font("Arial", 1, 13));
            lblRegPass.setFont(new java.awt.Font("Arial", 1, 13));
            lblRegAccPass.setFont(new java.awt.Font("Arial", 1, 13));
            lblRegPhone.setFont(new java.awt.Font("Arial", 1, 13));
            btnRegConfirm.setFont(new java.awt.Font("Arial", 1, 13));
            lblLanguageSelect.setFont(new java.awt.Font("Arial", 1, 36));
            btnLanguageSelect.setFont(new java.awt.Font("Arial", 1, 13));
            lblLoginTitle.setFont(new java.awt.Font("Arial", 1, 36));
            btnLoginConfirm.setFont(new java.awt.Font("Arial", 1, 13));
            
        } else if (RadioJapanese.isSelected()) {  // 일본어
            lblMainTitle1.setText("JAVA銀行");
            btnLogin.setText("ログイン");
            btnRegister.setText("会員登録");
            lblATMTitle.setText("JAVA銀行");
            btnDeposit.setText("お預入れ");
            btnWithdraw.setText("お引出し");
            btnLanguage.setText("言語設定");
            btnTransfer.setText("ご送金");
            btnView.setText("照会");
            btnRank.setText("残高ランキング");
            lblDepoTitle.setText("JAVA銀行");
            lblDepoAmount.setText("金額");
            lblDepoPass.setText("暗証番号");
            btnDepoConfirm.setText("確定");
            lblWithTitle.setText("JAVA銀行");
            lblWithAmount.setText("金額");
            lblWithPass.setText("暗証番号");
            btnWithConfirm.setText("確定");
            lblTransTitle.setText("JAVA銀行");
            lblTransAcc.setText("宛先口座");
            lblTransAmount.setText("金額");
            lblTransPass.setText("暗証番号");
            btnTransConfirm.setText("이체");
            lblViewAcc.setText("口座番号");
            lblViewName.setText("お名前");
            lblViewBalance.setText("口座残額");
            lblRegTitle.setText("JAVA銀行 会員登録");
            lblRegName.setText("お名前");
            lblRegID.setText("ID");
            lblRegPass.setText("パスワード");
            lblRegAccPass.setText("暗証番号");
            lblRegPhone.setText("携帯番号");
            btnRegConfirm.setText("会員登録");
            lblLanguageSelect.setText("言語選択");
            btnLanguageSelect.setText("選択");
            lblLoginTitle.setText("JAVA銀行");
            btnLoginConfirm.setText("ログイン");
            
            lblMainTitle1.setFont(new java.awt.Font("Yu Mincho", 1, 36));
            btnLogin.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            btnRegister.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblATMTitle.setFont(new java.awt.Font("Yu Mincho", 1, 36));
            btnDeposit.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            btnWithdraw.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            btnLanguage.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            btnTransfer.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            btnView.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            btnRank.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblDepoTitle.setFont(new java.awt.Font("Yu Mincho", 1, 36));
            lblDepoAmount.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblDepoPass.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            btnDepoConfirm.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblWithTitle.setFont(new java.awt.Font("Yu Mincho", 1, 36));
            lblWithAmount.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblWithPass.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            btnWithConfirm.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblTransTitle.setFont(new java.awt.Font("Yu Mincho", 1, 36));
            lblTransAcc.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblTransAmount.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblTransPass.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            btnTransConfirm.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblViewAcc.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblViewName.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblViewBalance.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblRegTitle.setFont(new java.awt.Font("Yu Mincho", 1, 36));
            lblRegName.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblRegID.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblRegPass.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblRegAccPass.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblRegPhone.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            btnRegConfirm.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblLanguageSelect.setFont(new java.awt.Font("Yu Mincho", 1, 36));
            btnLanguageSelect.setFont(new java.awt.Font("Yu Mincho", 1, 15));
            lblLoginTitle.setFont(new java.awt.Font("Yu Mincho", 1, 36));
            btnLoginConfirm.setFont(new java.awt.Font("Yu Mincho", 1, 15));  
            
            
        }
    }//GEN-LAST:event_btnLanguageSelectActionPerformed
    
    public String transfer(String accNo, int amount) throws IOException, SQLException {
        DBM.dbOpen(); // 디비 열고
        String strSQL = "SELECT * FROM user WHERE accountno = '" + accNo + "'"; // 이체 상대 찾는 SQL문
        DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
        
        if (DBM.DB_rs.next()) {  // 상대 계좌번호가 DB에 존재하는가?
            String name = DBM.DB_rs.getString("name");  // 이체 받는 사람 이름
            int balance = Integer.parseInt(DBM.DB_rs.getString("balance"));  // 이체 받는 사람 계좌 잔액
            balance += amount;  // 이체 받은만큼 잔고 더해줌
            
            String updateSQL = "UPDATE user SET balance = " + balance + " WHERE accountno = '" + accNo + "'";
            DBM.DB_stmt.executeUpdate(updateSQL);  // 상대 계좌 잔액 갱신
            return name;
            
        } else {
            JOptionPane.showMessageDialog(null, "상대 계좌번호가 없습니다.");
            return null;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ATMFrame;
    private javax.swing.JFrame DepositFrame;
    private javax.swing.ButtonGroup GroupLanguage;
    private javax.swing.JFrame LanguageFrame;
    private javax.swing.JFrame LoginFrame;
    private javax.swing.JRadioButton RadioEnglish;
    private javax.swing.JRadioButton RadioJapanese;
    private javax.swing.JRadioButton RadioKorean;
    private javax.swing.JFrame RankFrame;
    private javax.swing.JFrame RegisterFrame;
    private javax.swing.JFrame TransferFrame;
    private javax.swing.JFrame ViewFrame;
    private javax.swing.JFrame WithdrawFrame;
    private javax.swing.JButton btnDepoConfirm;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnLanguage;
    private javax.swing.JButton btnLanguageSelect;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginConfirm;
    private javax.swing.JButton btnRank;
    private javax.swing.JButton btnRegConfirm;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnTransConfirm;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnWithConfirm;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblATMTitle;
    private javax.swing.JLabel lblDepoAmount;
    private javax.swing.JLabel lblDepoPass;
    private javax.swing.JLabel lblDepoTitle;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLanguageSelect;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblMainTitle1;
    private javax.swing.JLabel lblMainTitle2;
    private javax.swing.JLabel lblRegAccPass;
    private javax.swing.JLabel lblRegID;
    private javax.swing.JLabel lblRegName;
    private javax.swing.JLabel lblRegPass;
    private javax.swing.JLabel lblRegPhone;
    private javax.swing.JLabel lblRegTitle;
    private javax.swing.JLabel lblTransAcc;
    private javax.swing.JLabel lblTransAmount;
    private javax.swing.JLabel lblTransPass;
    private javax.swing.JLabel lblTransTitle;
    private javax.swing.JLabel lblViewAcc;
    private javax.swing.JLabel lblViewBalance;
    private javax.swing.JLabel lblViewName;
    private javax.swing.JLabel lblWithAmount;
    private javax.swing.JLabel lblWithPass;
    private javax.swing.JLabel lblWithTitle;
    private javax.swing.JTextArea tAreaRank;
    private javax.swing.JTextArea tAreaView;
    private javax.swing.JTextField txtDepoAmount;
    private javax.swing.JTextField txtDepoPass;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtRegAccPass;
    private javax.swing.JTextField txtRegID;
    private javax.swing.JTextField txtRegName;
    private javax.swing.JTextField txtRegPass;
    private javax.swing.JTextField txtRegPhone;
    private javax.swing.JTextField txtTransAcc;
    private javax.swing.JTextField txtTransAmount;
    private javax.swing.JTextField txtTransPass;
    private javax.swing.JTextField txtViewAcc;
    private javax.swing.JTextField txtViewBalance;
    private javax.swing.JTextField txtViewName;
    private javax.swing.JTextField txtWithAmount;
    private javax.swing.JTextField txtWithPass;
    // End of variables declaration//GEN-END:variables
}
